# Generated by Django 5.0.3 on 2024-03-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='full_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
